set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR "C2000")
set(CMAKE_CROSSCOMPILING True)


set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER $ENV{CG_TOOL_ROOT}/bin/cl2000)
set(CMAKE_ASM_COMPILER $ENV{CG_TOOL_ROOT}/bin/cl2000)
set(CMAKE_CXX_COMPILER $ENV{CG_TOOL_ROOT}/bin/cl2000)

set(CMAKE_GENERATE_HEX $ENV{CG_TOOL_ROOT}/bin/hex2000 CACHE INTERNAL "Hex Generation tool")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

